### ISSUE TITLE
Day 03 - EC2 Instance

### ISSUE THREAD

**Issue by kthorri** [hgop/syllabus-2022#1]
Each group should leave comment here:

Team Name: dreamteam
Repository: your-private-github-repository
Where the Team Name is something unique (hasn't been commented before).

We'll setup an EC2 instance on AWS for you that you will install microk8s on.
We'll setup a CNAME record for dns so that team-name.hgopteam.com will point to your ec2 instance.
We will put a thumbs up on your comment once its done. Make sure you've added @Fanneyyy, @ironpeak and @kthorri to your project repository, so we can share the instance key with you.

Your instance key is private, it should not be shared outside your team.

**Comment by kthorri** [comment]
Team Name: dreamteam
Repository: https://github.com/kthorri/hgop-2022

**Comment by Sigurgeirstephensen** [comment]
Team Name: SmackMyTest
Repository: [Quality-Assurance---course](https://github.com/Sigurgeirstephensen/Quality-Assurance---course.git)
![image](https://user-images.githubusercontent.com/70693413/203082493-8f25f0f1-4375-41bd-a5b7-ee0b70b624cd.png)

**Comment by sveppalicious** [comment]
Team Name: BearForceOne
Repository: https://github.com/sveppalicious/HGOP

**Comment by magga-sola** [comment]
Team Name: bibibi
Repository: https://github.com/magga-sola/HGOP_2022
🐸

**Comment by PeturSteinn** [comment]
**Team Name:**
BadAddress

**Team Members:** 
Pétur Steinn Guðmundsson, petursg20@ru.is
Valdimar John Parks, valdimarp20@ru.is

**Repository:**
https://github.com/PeturSteinn/T-542-HGOP

**Comment by finnure** [comment]
**Team Name:** klauvey
**Repository:** https://github.com/finnure/hgop2022

**Comment by johann9898** [comment]
Team Name: Tester le croissant
Repository: https://github.com/johann9898/hgop

Team Memeber: 
Jóhann Rúnarsson
Ísar Daði Pálsson

**Comment by KypsLloyd** [comment]
team name: kyplerteam
repository:  https://github.com/KypsLloyd/hgop_kypler

**Comment by aronjohanns** [comment]
**Team name:** Jólaöl
**Repository:** https://github.com/aronbj20/hgop

**Team Members**
Aron Bergur Jóhannsson

**Comment by ironpeak** [comment]
Some of you have not given us access to the repository yet :crying_cat_face:

**Comment by gislibh** [comment]
**Team name: ** Insomniacs
**Repository: ** https://github.com/gislibh/hgop
**Team members: ** Gísli Bragi Hjartarson

**Comment by ghost** [comment]
Team Name: Nebula
Repository: https://github.com/baldurfb/hgop

**Comment by siggibjarna** [comment]
Team Name: nope
Repository: https://github.com/siggibjarna/ru-hgop

**Comment by hap2000** [comment]
Team Name: hap
Repository: https://github.com/hap2000/hgop2022

**Comment by omarpa** [comment]
Team Name: TMNT
Team Members: Arnar Ívarsson , Ómar Pálsson
Repository:   https://github.com/arnari/TMNT

**Comment by arnarthor** [comment]
Team Name: fireplaces
Repository: https://github.com/arnarthor/hgop

**Comment by Sindrit17** [comment]
Team Members: Gísli Guðmundsson, Sindri Snær Þorsteinsson
Team name: Gissinn
Repository: https://github.com/gislig/T-542-HGOP-2022

**Comment by k0rm** [comment]
Team name: slagathor
Team members: Kormákur Hjaltason, Alexander Þór Gíslason
Repository: https://github.com/k0rm/hgop-1337

**Comment by patrekurs19** [comment]
Team name: onyx
Team members: Patrekur Ingi Sigfússon
Repository: https://github.com/patrekurs19/HGOP

**Comment by Hjortur17** [comment]
Team name: Bears. Beets. Battlestar Galactica
Repository: https://github.com/Hjortur17/HR_HGOP

**Team Members**
Hjörtur Freyr Lárusson

**Comment by halldorvalberg** [comment]
Team name: Twoflower
Repository: [github.com/halldorvalberg/](https://github.com/halldorvalberg/T-542-HGOP)

**Comment by omarpa** [comment]
> Some of you have not given us access to the repository yet crying_cat_face 

Team Name: TMNT
Team Members: Arnar Ívarsson , Ómar Pálsson
Repository:   https://github.com/arnari/TMNT

_Originally posted by @omarpa in https://github.com/hgop/syllabus-2022/issues/1#issuecomment-1324135888_

**Comment by ElinVilbergs** [comment]
Team Name: Sykurmamma
Repository: https://github.com/ElinVilbergs/hgop22
