### ISSUE TITLE
Error when running microm8s in ssh and .kubu is removed

### ISSUE THREAD

**Issue by johann9898** [hgop/syllabus-2022#13]
Hi, I got error when running microm8s in the SSH environment. I thought deleting .kube would fix that.
Is it possible to somehow get .kube back? 
![image](https://user-images.githubusercontent.com/11422396/203608454-9f0ed5e1-625e-4018-a5d8-65e9beb2a34e.png)

**Comment by kthorri** [comment]
Have you tried going through all the steps again for [day3](https://github.com/hgop/syllabus-2022/blob/main/assignments/week-01/day-03/README.md)

**Comment by johann9898** [comment]
yes, i did but somehow i cant get .kube back into the ssh.

**Comment by johann9898** [comment]
> Have you tried going through all the steps again for [day3](https://github.com/hgop/syllabus-2022/blob/main/assignments/week-01/day-03/README.md)

yes, i did but somehow i cant get .kube back into the ssh and error is still there.

**Comment by kthorri** [comment]
After installing microk8s again, still no config file?

**Comment by johann9898** [comment]
> After installing microk8s again, still no config file?

Nope

**Comment by kthorri** [comment]
Without having much understanding on what exactly happened.

Did you delete the .kube file you saved locally? Or did you delete some config file from the ec2?
What was the error you received before deleting .kube?
Did you ever manage to make everything work? Prior to getting error and deleting config.

I would suggest that you reinstall everything again to the ec2. And see if that works.

It is kind-of hard to manage these things async, so if this combined with some google tests doesn't work, I think we might need to take a look at this in the practical session.

**Comment by johann9898** [comment]
> Without having much understanding on what exactly happened.
> 
> Did you delete the .kube file you saved locally? Or did you delete some config file from the ec2? What was the error you received before deleting .kube? Did you ever manage to make everything work? Prior to getting error and deleting config.
> 
> I would suggest that you reinstall everything again to the ec2. And see if that works.
> 
> It is kind-of hard to manage these things async, so if this combined with some google tests doesn't work, I think we might need to take a look at this in the practical session.

So at first there was error in ssh environment when i was trying to run microk8s, i thought deleting .kube would fix it. but now i deleted the .kube, https://httpbin.testerlecroissant.hgopteam.com/ and https://httpbin.testerlecroissant.hgopteam.com/. won't work. what was inside of .kube was deployment folder and HTTP folder. 

![image](https://user-images.githubusercontent.com/11422396/203615791-98960f20-73a5-4311-a0a0-31f096dda612.png)

When i try to do this all again, I still get errors now and nothing works with microk8s and still missing .kube in the ssh file

**Comment by johann9898** [comment]
> > Without having much understanding on what exactly happened.
> > Did you delete the .kube file you saved locally? Or did you delete some config file from the ec2? What was the error you received before deleting .kube? Did you ever manage to make everything work? Prior to getting error and deleting config.
> > I would suggest that you reinstall everything again to the ec2. And see if that works.
> > It is kind-of hard to manage these things async, so if this combined with some google tests doesn't work, I think we might need to take a look at this in the practical session.
> 
> So at first there was error in ssh environment when i was trying to run microk8s, i thought deleting .kube would fix it. but now i deleted the .kube, https://httpbin.testerlecroissant.hgopteam.com/ and https://httpbin.testerlecroissant.hgopteam.com/. won't work. what was inside of .kube was deployment folder and HTTP folder.

![image](https://user-images.githubusercontent.com/11422396/203615791-98960f20-73a5-4311-a0a0-31f096dda612.png)

When i try to do this all again, I still get errors now and nothing works with microk8s and still missing .kube in the ssh file

**Comment by johann9898** [comment]
Is it possible to get brand new ssh access with rsa key?

**Comment by ironpeak** [comment]
Created a fresh instance, same url and key
