### ISSUE TITLE
Certifacate

### ISSUE THREAD

**Issue by omarpa** [hgop/syllabus-2022#14]
![image](https://user-images.githubusercontent.com/5538849/203657850-5b6c467b-d496-47eb-b5f3-f4386a679473.png)

Eiga acme letsencryp certin ekki að vera alveg valid ? 
Eru fleiri að fá þau svona ?    

https://connect4.tmnt.hgopteam.com/

**Comment by aronjohanns** [comment]
Staging certifcatið ætti ekki að vera valid. En production certificatið á að virka. Mig minir að ég þurfti að restarta: 
```bash
kubectl delete pod httpbin-86956d44c4-qt27d
```
þar sem httpbin-86956d44c4-qt27d er ykkar pod
```bash
kubectl get pods
```

**Comment by finnure** [comment]
Ég lenti í því sama. Hoppaði yfir eftirfarandi línur, gleymdi að eyða út:
```bash
kubectl delete clusterissuer letsencrypt-staging
kubectl delete ingress httpbin
kubectl delete secret httpbin-tls-staging
```
Ef þú eyðir ingress og býrð það til aftur með production stillingum ætti þetta að lagast... ef það sem Aron stakk uppá var ekki nóg.

**Comment by kthorri** [comment]
@omarpa ég loka þessu, þar sem það virðast vera komin góð svör við spurningunni nú þegar. Þú mátt endilega opna aftur og tagga mig ef þetta er óleyst
