### ISSUE TITLE
Error loading config file 

### ISSUE THREAD

**Issue by thoreyosk** [hgop/syllabus-2022#16]
# Expected Behaviour
I am trying to run "kubectl get namespaces" after I made the .kube/config file to get this:
NAME              STATUS   AGE
kube-system       Active    5m
kube-public       Active    5m
kube-node-lease   Active    5m
default           Active    5m
ingress           Active    5m

# Current Behaviour
error: error loading config file "/Users/thoreyosk/.kube/config": yaml: line 6: could not find expected ':'

## Context

* Operating System: macOS Monterey Version 12.6.1
* Processor: 1,8 GHz Dual-Core Intel Core i5

I've cleared the config file and pasted everything in again, I've compared it line by line with the one I copied and everything is the same. I've deleted the whole file and created it again. My teammate took that exact same text and made the config file on his computer and everything works there. 

Any ideas?

**Comment by ghost** [comment]
I had a similar problem. The YAML parser is failing due to a formatting issue.

To fix this I used a YAML linter to locate the issue; for me it was a line break in an inappropriate place. It is likely something similar in your case. This can happen on your end while not happening on your teammates computer because even copy-pasting doesn't always keep the correct formatting.

**Comment by ghost** [comment]
I just recreated my issue and it was the exact same as yours. The certificate-authority-data key copies across into two lines, when it must be all on one line. Remove the extra line break and everything should work.

Out of curiosity what is your teammates OS?

**Comment by finnure** [comment]
> 

I'm the teammate. We are both on macos. I used vim, Þórey used nano 🤷

**Comment by ghost** [comment]
I just tried vim and some other text editors, and copy pasting works perfectly for me there. So I think this is a nano issue then.

**Comment by kthorri** [comment]
@thoreyosk can you confirm that using some other text editor worked for you?

Are we saying that nano is the fault here?

**Comment by kthorri** [comment]
I'm closing this - please open again if not resolved

**Comment by thoreyosk** [comment]
This worked after I installed VIM, deleted the config file and created a new one with VIM instead of Nano. 
Thanx!
