### ISSUE TITLE
502 Bad Gateway when trying to get Connect4 up and running - Day 03 

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#19]
# Expected Behaviour
I am trying to get <code>connect4.{{team-name}}.hgopteam.com</code> up and running.

# Current Behaviour
I am getting a 502 Bad Gateway each time I visit the site. Looks like it some issue with the nginx engine. What part of the .yaml file do I have to look out for?

## Context

* Operating System: MacOS

## Failure Logs

![Screenshot 2022-11-24 at 13 29 16](https://user-images.githubusercontent.com/19752446/203796107-8184cc4e-4dea-471b-8910-1c9b800b466f.png)

**Comment by patrekurs19** [comment]
Same thing happened to me, make sure that the container port (located in the deployment file) is the same as the one you used in day 2. For me it was port 3000.

**Comment by kthorri** [comment]
Does httpbin work correctly?

What is the output when you log your connect4 deployment?

**Comment by Fanneyyy** [comment]
Hey, you can investigate the pod by doing:
`kubectl get pods`
`kubectl logs POD_NAME_FROM_PREVIOUS`

If the logs show that the app is running on port X. It's most likely that the port is not being properly mapped.

**Comment by Hjortur17** [comment]
> Does httpbin work correctly?
> 
> What is the output when you log your connect4 deployment?

Yes it works fine.


When I do <code>kubectl logs POD_NAME</code>, I get this: 

```
> connect4-client@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

**Comment by patrekurs19** [comment]
Try changing the container port (deployment file) and the target port (service file) to 3000

**Comment by Hjortur17** [comment]
Thanks! That solved it.

Though the target port was suppose to be 80

**Comment by Hjortur17** [comment]
Hvað getur verið að valda því að ég sé að fá 502 eftir að hafa reynt að setja upp TLS?

**Comment by finnure** [comment]
Þegar þú settir tls stillingarnar inn, tókstu hinar stillingarnar út? 
annotations á að bætast við undir metadata, það sem var fyrir undir metadata á að vera áfram eins.
tls á að bætast við undir spec. rules á að vera óbreytt undir spec áfram.
hosts undir tls þarf að vera rétt miðað við urlið á þjónustunni.

**Comment by Hjortur17** [comment]
Hérna eru báðar þjónusturnar mínar. Tók ekkert út, bæti bara við.

Httpbin þjónustan virkar fínt en connect4 fær alltaf 502 Bad Gateway

Hérna eru ingress skrárnar úr báðum þjónustunum:
![Screenshot 2022-11-24 at 19 25 45](https://user-images.githubusercontent.com/19752446/203854035-cef45fd9-200a-4294-9d9d-d8c77a330ea9.png)

**Comment by Hjortur17** [comment]
Ein pæling, þegar ég geri <code>kubectl get certificate</code> fæ ég þessa niðurstöðu:
```
NAME           READY   SECRET         AGE
connect4-tls   True    connect4-tls   4h6m
```

Ætti ég ekki að fá báðar þjónusturnar?

**Comment by finnure** [comment]
Jú, þú ættir að sjá bæði. Svona kemur þetta hjá mér:
```bash
NAME           READY   SECRET         AGE
connect4-tls   True    connect4-tls   20h
httpbin-tls    True    httpbin-tls    20h
```

**Comment by Hjortur17** [comment]
Náði að fá bæði upp með að færa <code>letsencrypt.yaml</code> yfir í <code>/src</code>. Núna er ég bara að bíða eftir að það kemur <code>READY True</code>...

**Comment by Hjortur17** [comment]
Virkaði greinilega að færa <code>letsencrypt.yaml</code> yfir í <code>/src</code>
