### ISSUE TITLE
Day 1 easy points 

### ISSUE THREAD

**Issue by Sigurgeirstephensen** [hgop/syllabus-2022#2]
Team Name: SmackMyTest
Repository: [Quality-Assurance---course](https://github.com/Sigurgeirstephensen/Quality-Assurance---course.git)
![ba927ff34cd961ce2c184d47e8ead9f6](https://user-images.githubusercontent.com/70693413/203077576-c12dd387-4677-4c0a-a26d-a6a02b5b455a.jpg)

**Comment by piotr20a** [comment]
.

**Comment by kthorri** [comment]
Let me in

**Comment by kthorri** [comment]
Waste of time, not considered
