### ISSUE TITLE
Key errors with SSH

### ISSUE THREAD

**Issue by Isardadi00** [hgop/syllabus-2022#20]
ssh -i "~/.aws/keys/testerlecroissant.pem" [ubuntu@testerlecroissant.hgopteam.com](mailto:ubuntu@testerlecroissant.hgopteam.com)

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: POSSIBLE DNS SPOOFING DETECTED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ECDSA host key for testerlecroissant.hgopteam.com has changed,
and the key for the corresponding IP address 54.154.194.196
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:BO9tSX/+xnUJpVQDJGW6829YBNcXkX6t6qBIakXOH2A.
Please contact your system administrator.
Add correct host key in /home/isard/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/isard/.ssh/known_hosts:1
remove with:
ssh-keygen -f "/home/isard/.ssh/known_hosts" -R "testerlecroissant.hgopteam.com"
ECDSA host key for testerlecroissant.hgopteam.com has changed and you have requested strict checking.
Host key verification failed.

What can we do here ?
Using the same key that we´re given in the issue.
We´ve changed nothing on our end and now it doesn´t work.

**Comment by Isardadi00** [comment]
@ironpeak Væri hægt að fá svar við þessu sem fyrst? Bókstaflega það eina sem við eigum eftir og heldur okkur frá því að klára verkefnið.

Kubernetes clusterinn er ekki keyrandi og þurfum að komast inn til að laga það.

**Comment by ironpeak** [comment]
ssh-keygen -f "/home/isard/.ssh/known_hosts" -R "testerlecroissant.hgopteam.com"
