### ISSUE TITLE
Error when trying to publish my image to Docker Hub using CircleCI

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#21]
# Expected Behaviour
I am trying to publish my image to Docker Hub using CircleCI. 

# Current Behaviour
Getting error when CircleCI is publishing to my hub. NOTE: I have stored the username, password and image name in an env variable in CircleCI

## Context

* MacOS

## Failure Logs

![Screenshot 2022-11-24 at 21 25 22](https://user-images.githubusercontent.com/19752446/203865333-43d95bc7-442d-4b0e-a749-508550f1f0e1.png)

**Comment by finnure** [comment]
Tag does not exist þýðir að þegar þú keyrðir docker build í pípunni settir þú ekki rétt tag á image sem var buildað. Annaðhvort þarftu að bæta við `:${CIRCLECI_SHA1}` sem tag í build skipunina, eða bæta við auka skrefi áður en þú keyrir docker push þar sem þú býrð þetta tag til.

**Comment by Hjortur17** [comment]
Það passaði, var að notast við <code>:part2</code> en ekki <code>:${CIRCLECI_SHA1}</code>
