### ISSUE TITLE
is yarn.lock required?

### ISSUE THREAD

**Issue by siggibjarna** [hgop/syllabus-2022#22]
I don't have the `./src/connect4-client/yarn.lock` file in my repo, but it's listed in the assignment, so is it required?

**Comment by ghost** [comment]
No, it is probably not required. Yarn is a superior alternative to npm. Since the assignments don't mention yarn at all; we can assume that using npm only is fine.

**Comment by siggibjarna** [comment]
That's my thinking as well, just wanted confirmation from the TAs 😉

**Comment by Fanneyyy** [comment]
Hey, yes correct, no `yarn.lock` needed, updated to `package-lock.json`
