### ISSUE TITLE
kubectl version check

### ISSUE THREAD

**Issue by Tanges** [hgop/syllabus-2022#23]
Er ekki að ná að bæta við í verify bash scriptuna að checka fyrir kubectl, eruði með einhver ráð?
kubectl version --short skilar Client, Kustomize og Server version en veit ekki hvað á að bera saman við.
Einnig er ég að nota dpkg-query til að checka hvort það sé uppsett en það kemur bara "dpkg-query: package 'kubectl' is not installed and no information is available" þó það sé sett upp.

**Comment by finnure** [comment]
Ég er að nota `kubectl version --client --short` til að sækja version hjá mér. Það skilar bæði client og Kustomize versionum í sitthvorri línunni. Með því að nota `... | head -n 1` aftast í skipuninni fæ ég bara client version línuna.

**Comment by sveppalicious** [comment]
Ég spurði út í þetta í issue #6, en fékk líka nánari svar í dæmatíma að það væri nóg að checka hvort að Client version væri v1.0.0 eða hærra.

**Comment by Tanges** [comment]
Snilld! Þá ættum við að vera með þetta.
