### ISSUE TITLE
Error when doing npm run dev

### ISSUE THREAD

**Issue by johann9898** [hgop/syllabus-2022#25]
![image](https://user-images.githubusercontent.com/11422396/204290677-e35031a5-a4fe-48b7-8622-5057fcc48173.png)

im getting this error, and idk how to fix this.

**Comment by finnure** [comment]
What node version do you have installed? I think the ?? operator was introduced in version 18. If you have an older version, that might be the reason.

**Comment by johann9898** [comment]
Thanks, it works when i update the nodejs.
