### ISSUE TITLE
Enviromental variable not working

### ISSUE THREAD

**Issue by patrekurs19** [hgop/syllabus-2022#26]
the get request is always sent to the client url not the server url 
ive tried to use env in deployment and ive tried to use envFrom, neither seems to be working
deployment:
![image](https://user-images.githubusercontent.com/58478764/204327019-137322ea-89af-4ca8-b7c4-9a22ee0b9134.png)
config map:
![image](https://user-images.githubusercontent.com/58478764/204327134-83dd6c0c-f491-4c88-8cd9-d83aae03832e.png)

**Comment by Fanneyyy** [comment]
Can't see anything wrong with this config, this is def in the client folder right (i.e. the config map)?
I see your client is called connect4 and server connect4-server, could you make sure you're only deploying one pod for the client, i.e. if you check `kubectl get pods`?

**Comment by patrekurs19** [comment]
This is the folder set up, the file is in the k8s folder:
![image](https://user-images.githubusercontent.com/58478764/204342030-6116db6e-cf8d-47f4-a365-8380ff608ea5.png)

And this is the response to kubectl get pods:
![image](https://user-images.githubusercontent.com/58478764/204341879-1318788c-37bb-4e8d-8003-f097c0477463.png)

**Comment by Fanneyyy** [comment]
Think we might need to take a look at this tomorrow in class, this should not stop you from moving to the server part, i.e. add the server, create the database and create build/publish/deploy steps for the server in Circle CI and hopefully we can figure this out tomorrow 😊
