### ISSUE TITLE
EC2 instance - No such file or directory

### ISSUE THREAD

**Issue by ElinVilbergs** [hgop/syllabus-2022#29]
I got my EC2 instance on friday, everytime I try to change the permission to my keyfile or ssh into the ec2 instanse, I get "No such file or directory" error. I've replaced {{team-name}} with the team name I commented. 
Is there a step that I'm missing or..?
(Haven't been able to come to lab because I've been really sick for the past few days)

**Comment by Fanneyyy** [comment]
Is the key located under `~/.aws/keys` ?

**Comment by ElinVilbergs** [comment]
No, if I cd into the .aws directory I only get 'credentials'. 

![Screenshot 2022-11-29 at 20 41 14](https://user-images.githubusercontent.com/34030656/204643117-aa752f89-ab35-402d-aec6-7d85551d01a5.png)

I can try to swing by the lab class tomorrow

**Comment by ElinVilbergs** [comment]
I figured it out - didn't realize I had to create the keys folder and the pem file myself haha ':)
