### ISSUE TITLE
NPX before NPM is installed 

### ISSUE THREAD

**Issue by Sigurgeirstephensen** [hgop/syllabus-2022#3]
I am trying to do npx for assignment two because we need to do that before we do anything 
but I don't have npm installed on my mac, so it can't do npx 
I am on a new MacBook Air and do a monthly cleanup of my computer, so I delete packages 

 In the assignment today, you tell us to do npx create-next-app@latest connect4-client --typescript, but this is impossible before you do npm install or brew npm, so I feel like it should say before you do npx that we need to download npm otherwise, npx isn't installed on the system, or npm isn't updated enough. Still, I guess yesterday's project made us do npm install, but this is for testing and needs to be accessible to people, so everything needs to be worded correctly.
 
 So i really feel like we should add that you need to install npm on the same place we install docker

**Comment by kthorri** [comment]
Did your script not notify that you didn't have npm installed when completing the task in [day 1](https://github.com/hgop/syllabus-2022/tree/main/assignments/week-01/day-01)?

**Comment by arnarthor** [comment]
I think it's fair to assume throughout this course that all assignments build on the previous ones, so in this case, since day 1 stated that you need to verify that npm is installed, then you should have npm available in the second days assignment.
