### ISSUE TITLE
Can't see what's failing with my test

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#35]
# Expected Behaviour
Trying to write Python test

# Current Behaviour
Having a hard time figuring out what is failing (See picture below).

Here is for example my <code>is_victory_move_horizontal</code> function
```
def is_victory_move_horizontal(game: models.Game, x: int, y: int, player: models.Player) -> bool:
    winner = False
            
    if game.board[x][y] == player and game.board[x][y+1] == player and game.board[x][y+2] == player and game.board[x][y+3] == player:
        winner = True

    return winner
```

And here is the test:

```
def test_make_move_vertical_win_one():
    game_input = helper.get_initial_game_state()
    game_input.board[0][0] = Tile.ONE
    game_input.board[0][1] = Tile.ONE
    game_input.board[0][2] = Tile.ONE

    game_output = game_logic.make_move(game_input, 0)

    assert False == game_output.active
    assert Player.ONE == game_output.winner
```

What I don't understand is why it's always asserting False == True. Should I be returning 1 or 2 (int)? 

## Failure Logs

![Screenshot 2022-11-30 at 13 32 15](https://user-images.githubusercontent.com/19752446/204809444-47dadb9a-ae8d-433e-b26b-03ed4abff6e0.png)

**Comment by finnure** [comment]
When you call game_logic.make_move, you're adding a fourth tile to the column that will be put in x=0, y=3. When make_move calls your is_victory_move_horizontal, x=0 and y=3. Your check method checks y = 3, 4, 5 and 6 but should instead check y = 3, 2, 1 and 0.

You are returning the correct type, you should return either True or False, not 1 or 2.

**Comment by finnure** [comment]
Also you are mixing up horizontal and vertical functionality. Horizontal should change x and keep y constant, vertical should keep x constant and change y.
When checking horizontal, you need to keep in mind that you need to change  x in both directions. Horizontal is a bit more complicated than vertical.

**Comment by Hjortur17** [comment]
Okay thanks for explaining so well! 

But do we know how large the board is? Like the max length? So I can make for loop that runs from 0 - MAX to check on x.

So I can think of x as rows and y as columns?

**Comment by finnure** [comment]
x is columns, y is rows.
x ranges from 0-6, total of 7 columns, 0 being the left most and 6 the right most.
y ranges from 0-5, total of 6 rows, 0 being bottom row and 5 top row.

game.board[0][0] is bottom left
game.board[6][5] is top right
