### ISSUE TITLE
no prompt when run npm run lint

### ISSUE THREAD

**Issue by patrekurs19** [hgop/syllabus-2022#37]
I tried to run npm run lint but didnt get the prompt to set up the rules

**Comment by finnure** [comment]
That's most likely because you already have an `.eslintrc.json` file. If you want to get the prompt, delete the `.eslintrc.json` file and try running `npm run lint` again.

**Comment by Hjortur17** [comment]
I had the same issue, I had to delete the <code>.eslintrc.json</code> and run the command again. Then I got the prompt

**Comment by kthorri** [comment]
You don't need the prompt. No need to delete eslint file
