### ISSUE TITLE
leiðilegt villa

### ISSUE THREAD

**Issue by Sigurgeirstephensen** [hgop/syllabus-2022#39]
við höldum áfram að lenda í þessu vandamáli TA er búin að reyna að finna hvað þetta vandamál er en enginn laus hefur verið fundið server nær samt að runna og við getum spilað leikinn en pipeline er ekki alveg að leyfa okkur að segja að dagur er búin ```
deployment.apps/smackmytest configured
ingress.networking.k8s.io/smackmytest unchanged
service/smackmytest configured
configmap/connect4-server unchanged
deployment.apps/connect4-server configured
ingress.networking.k8s.io/connect4-server unchanged
job.batch/connect4-migrations created
service/connect4-server unchanged
deployment.apps/httpbin unchanged
ingress.networking.k8s.io/httpbin unchanged
service/httpbin unchanged
The request is invalid: patch: Invalid value: "map[data:map[DATABASE_PASSWORD:{{DATABASE_PASSWORD}} DATABASE_USERNAME:{{DATABASE_USERNAME}}] metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":{\"DATABASE_PASSWORD\":\"{{DATABASE_PASSWORD}}\",\"DATABASE_USERNAME\":\"{{DATABASE_USERNAME}}\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"connect4-server\"},\"name\":\"connect4-server\",\"namespace\":\"default\"}}\n]]]": error decoding from json: illegal base64 data at input byte 0

Exited with code exit status 1
```

**Comment by Sigurgeirstephensen** [comment]
<img width="1258" alt="Screenshot 2022-11-30 at 17 18 43" src="https://user-images.githubusercontent.com/70693413/204864804-06ba1896-29ef-4eee-a7ee-d7ee3aeda7fc.png">

**Comment by finnure** [comment]
Það lítur út fyrir að þegar þið keyrðuð create.sh þá var user og pass fyrir database ekki sett inn í staðinn fyrir placeholderana. Getur verið að það sé typo í environment variable name í circleci?
```bash
CONNECT4_SERVER_DATABASE_USERNAME=<base64 encoded username>
CONNECT4_SERVER_DATABASE_PASSWORD=<base64 encoded password>
```

**Comment by Sigurgeirstephensen** [comment]
við erum með það en það virkar ekki við náðum að laga með að hardcode en það mun ekki virka forever
