### ISSUE TITLE
Error in pipeline

### ISSUE THREAD

**Issue by johann9898** [hgop/syllabus-2022#40]
I'm getting this error from the pipeline.
![image](https://user-images.githubusercontent.com/11422396/204865449-7811d502-5dfd-4aff-a803-bca81e25bede.png)

I used the code and follow through from the day08 from here:
![image](https://user-images.githubusercontent.com/11422396/204868702-0a975760-cbe8-4fc9-b78f-c39b582a5431.png)

I don't know how to fix this problem/error.

**Comment by finnure** [comment]
You need to manually create the acceptance namespace. I don't know if it was intentionally left out of the instructions to make us have to figure it out, or if they just forgot to mention it 🤷‍♂️
```bash
kubectl create namespace acceptance
```

**Comment by johann9898** [comment]
Now there's this error. 
![image](https://user-images.githubusercontent.com/11422396/204890069-13b6f271-a328-43da-a5d7-f1f5c81fa594.png)

**Comment by finnure** [comment]
Been there, done that. Again, info missing or intentionally left out of the instructions :)
In ingress.template.yaml you probably hardcoded the url used for the service. This means that the acceptance instance will use the same exact url as your production one instead of the acceptance url you're trying to connect to, and won't be accessible because production is already using it.
What I did to solve this:
1. Add an environment variable in circleci: `CONNECT4_SERVER_HOST=<url from ingress>`
2. Create a placeholder in ingress.template.yaml, remove the hardcoded url (both of them) and replace it with `{{HOST}}`

**Comment by johann9898** [comment]
> Been there, done that. Again, info missing or intentionally left out of the instructions :) In ingress.template.yaml you probably hardcoded the url used for the service. This means that the acceptance instance will use the same exact url as your production one instead of the acceptance url you're trying to connect to, and won't be accessible because production is already using it. What I did to solve this:
> 
> 1. Add an environment variable in circleci: `CONNECT4_SERVER_HOST=<url from ingress>`
> 2. Create a placeholder in ingress.template.yaml, remove the hardcoded url (both of them) and replace it with `{{HOST}}`

What kind of placeholder do i need to create in ingress.template.yaml?

**Comment by finnure** [comment]
`{{HOST}}` is the placeholder
![image](https://user-images.githubusercontent.com/89914707/204895742-12f758fe-fe20-4400-ba3d-157513853cb9.png)

When running the `create.sh` script with connect4-server as first parameter, it will read all environment variables that start with `CONNECT4_SERVER_`, remove that part of the envrionment variable and search for all instances of `{{<restOfEnvVar>}}` in the yaml files and replace it with the value of the environment variable.
So the value in enviroment variable `CONNECT4_SERVER_HOST` will be used to replace `{{HOST}}`, just like `{{DATABASE_USERNAME}}` is replaced with the value of the environment variable `CONNECT4_SERVER_DATABASE_USERNAME`

**Comment by johann9898** [comment]
> CONNECT4_SERVER_DATABASE_USERNAME

Thank you so much! It solved the problem for me.
