### ISSUE TITLE
Næ ekki að nota requests í CircleCi

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#42]
# Expected Behaviour
Ég er að reyna að fá pipeline-ið til að virka á CircleCi

# Current Behaviour
Er búinn að bæta við <code>requests==2.28.1</code> í <code>requirements_dev.txt</code> en ég fæ alltaf villu um að CircleCi finnur það ekki (sjá mynd)

## Failure Logs

<img width="1300" alt="Screenshot 2022-12-01 at 10 04 09" src="https://user-images.githubusercontent.com/19752446/205024603-946c14d2-0c54-4cbb-b789-83d7dc368392.png">

**Comment by sveppalicious** [comment]
Ég bætti við `types-requests` pakkanum og þetta hætti að kvarta.

```text
mypy==0.991
pytest==7.2.0
pytest-cov==4.0.0
types-requests==2.28.11.5
requests==2.28.1
```

Ég veit ekki hvort þetta sé rétta leiðin til að gera þetta, en þetta virkaði allt eftir að ég bætti þessu við.
