### ISSUE TITLE
Deploy klúðrar í Step 2 - Deploy acceptance environment

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#49]
**Expect**
--------------------------------
Deploy

**Current**
------------------------
![image](https://user-images.githubusercontent.com/70693651/205186473-08388bd4-2419-4b5e-bdb4-d66c63fec079.png)

Allt virkar fyrir utan deploy :/
Getur einhver sagt mér hvað þetta þýðir eða hefur einhver líka lent í þessu?
google var lítið að hjálpa

Hefur þetta kannski einhvað að gera við?  Þetta er acceptance nefnilega  
![image](https://user-images.githubusercontent.com/70693651/205187181-ff8f7d72-3e4b-4e62-a91d-f775c1c81a5b.png)

**Comment by finnure** [comment]
Villan bendir til þess að það er eitthvað að í create.sh scriptinu. Gerðiru einhverja breytingu á því? Getur þú postað því?

**Comment by halldorvalberg** [comment]
Lennti í sama máli. Það sem lagaði það hjá mér var að inn í create.sh skjalinu. Lagaði til gæsalappirnar og villan fór. Í öllum sed aðgerðum eins og t.d. hérna: 
`env_prefix="$(echo ${SERVICE}- | awk '{print toupper($0)}' | sed "s/-/_/g")"
Að breyta "s/-/_/g" í 's/-/_/g'

**Comment by KypsLloyd** [comment]
svona lítur create.sh út, var að bæt underscore þar sem rauða örin er
![image](https://user-images.githubusercontent.com/70693651/205318146-d4d1619d-623e-4e1e-be36-184f87f2281d.png)


En þá fæ ég error í apply acceptance
![image](https://user-images.githubusercontent.com/70693651/205318285-5ba1dadb-45d1-4520-99a4-64fada91eee9.png)

**Comment by KypsLloyd** [comment]
Breyti gæsalöppum en fæ en þá sama error og hér fyir ofan í apply acceptance 

![image](https://user-images.githubusercontent.com/70693651/205323031-aae7db90-4116-49a0-a589-8981c5641d4d.png)

**Comment by finnure** [comment]
create.sh var gefin í einu skrefinu í syllabus. Það á ekki að breyta neinu í þessari skrá, hún á að vera nákvæmlega eins og hún var gefin upp. Þetta undirscore sem þú bættir við á ekki að vera.
Hérna er skráin eins og hún var gefin upp, er að virka hjá mér:
```bash
#!/bin/bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Invalid number of arguments"
    echo "./scripts/ci/deploy/create.sh <service> <tag>"
    exit 1
fi

SERVICE="$1"
TAG="$2"

env_prefix="$(echo ${SERVICE}- | awk '{print toupper($0)}' | sed 's/-/_/g')"
env_variables="$(printenv | { grep "${env_prefix}" || test $? = 1; } | sed "s/^${env_prefix}//g")"

content="$(./scripts/ci/yaml/merge.sh ./src/${SERVICE}/k8s)"

content="$(echo "${content}" | sed "s/{{IMAGE_TAG}}/${TAG}/g")"

for variable in ${env_variables}; do
    variable_key="$(echo "${variable}" | cut -d '=' -f1)"
    variable_value="$(echo "${variable}" | cut -d '=' -f2-)"
    content="$(echo "${content}" | sed "s/{{${variable_key}}}/${variable_value}/g")"
done

echo "${content}"
```

**Comment by KypsLloyd** [comment]
Yebb retrackið til baka í original og virkar núna. Það var eftir að ég lét keyra **create_acceptance_environment EFTIR publish og build!!**

**Comment by KypsLloyd** [comment]
Nevermind, er aftur að lenda í sömu villu..
create.sh er copy/paste af day6**


![image](https://user-images.githubusercontent.com/70693651/205333121-b199fd3f-0d6f-4986-af62-cfc87cb0907e.png)

Deployið lítur svona út hjá mér
![image](https://user-images.githubusercontent.com/70693651/205333226-e07f37a8-189d-4fb6-946e-1aa022ba7d86.png)


Hefur alltaf virkað hingað til :/

**Comment by KypsLloyd** [comment]
breytti kommur í prósentur
![image](https://user-images.githubusercontent.com/70693651/205335745-2bbc2e6e-7b13-4b32-9ef1-35aa094d5ff8.png)
