### ISSUE TITLE
Problem with launching python script

### ISSUE THREAD

**Issue by Tanges** [hgop/syllabus-2022#50]
![image](https://user-images.githubusercontent.com/2120907/205322017-d1a2ad25-caf7-48ba-9ed7-d0e0f0c6eb95.png)

Fæ alltaf ModuleNotFoundError fyrir connect4 í dev umhverfi en virkar á docker, er ég að gleyma einhverju?

**Comment by finnure** [comment]
Þú átt ekki að vera inní þessari möppu þegar þú keyrir forritið, þú átt að keyra það úr connect4-server möppunni svona:
```bash
python .\src\connect4\app.py
```
Varstu búinn að installa requirements? Ef ekki þarftu að byrja á því, aftur úr connect4-server möppunni:
```bash
pip install -r requirements.txt
pip install -r requirements_dev.txt
```
eða með því að nota just:
```bash
just install
```
Svo er alltaf sniðugast að keyra upp virtual environment fyrir python locally áður en þú gerir allt ofangreint.

**Comment by Tanges** [comment]
Já, auðvitað er ég röngum stað :)
Sýnist þetta gerast þar líka en ég nota bara docker til að prufa þetta, takk.
