### ISSUE TITLE
connect4-server ingress villa

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#51]
![image](https://user-images.githubusercontent.com/70693651/205335278-9a6cce38-7694-4efa-87dc-c9d80db2c411.png)

Held hann sé að kvart að ég sé ekki með base64 encoded Host name, en ég er með CONNECT4_SERVER_HOST með mínum server hlekk og ingress.template.yaml lítur svona út:
![image](https://user-images.githubusercontent.com/70693651/205335990-a4500012-f5e2-4c2d-9bf1-c99145199786.png)

**Comment by finnure** [comment]
Environment variable í circleci hjá mér er cleartext, ekki base64. Ég tók það sem var í ingress skránni fyrir og setti nákvæmlega það sem value, virkar svoleiðis. 
![image](https://user-images.githubusercontent.com/89914707/205336962-17965b31-4e28-4b65-a5a5-8f6ec13737d7.png)

**Comment by finnure** [comment]
Getur verið að þú hafir bætt https:// framaná? Það á ekki að vera

**Comment by KypsLloyd** [comment]
s.s. svona þá?

connect4-server.<<temname>>.hgopteam.com

**Comment by KypsLloyd** [comment]
Takk Finnur, virkaði
