### ISSUE TITLE
Næ að spila locally en ekki eftir deploy

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#52]
Þegar ég keyri upp connect4 client og serverinn minn locally og set viðeigandi hlekk í next.config.js , þá næ ég að spila.
En eftir að ég set svo connect4-server hlekkinn inn og deploy-a virkar ekki að byrja local co-op game.

locally sem virkar
----------
![image](https://user-images.githubusercontent.com/70693651/205342093-d9e45711-33ba-4e2b-8fce-3a7fef711672.png)
![image](https://user-images.githubusercontent.com/70693651/205342144-3810a2e2-a922-498f-9316-646ec3d02603.png)

cloud (eftir deploy) sem virkar ekki
----------
![image](https://user-images.githubusercontent.com/70693651/205342363-8010dd96-c256-4f85-917d-73a5487d6082.png)

Veit einhver af hverju?

**Comment by KypsLloyd** [comment]
Fæ þetta í consolenum þe´gar ég ýt á start local co-op game
![image](https://user-images.githubusercontent.com/70693651/205349829-8c98c024-5a06-4a43-9d85-ac255a479d55.png)

**Comment by omarpa** [comment]
Er í sama vesesni, allt kvöldið farið í þetta... ætti bara að vera einfalt CORS en alveg sama hvað ég reyni það virkar aldrei á þjóninum.    
CORS er samt stillt á server ekki client.
