### ISSUE TITLE
400 Bad request frá /create_game

### ISSUE THREAD

**Issue by gislibh** [hgop/syllabus-2022#53]
Testið í helper.py failar alltaf, serverinn er uppi en það er eins og þessi endapunktur virki ekki: 

![Screenshot from 2022-12-02 17-25-39](https://user-images.githubusercontent.com/89972115/205351387-5a60be1e-a513-4936-b506-08be37be2187.png)
![Screenshot from 2022-12-02 17-26-36](https://user-images.githubusercontent.com/89972115/205351423-d0fc367b-bdaf-40f6-b570-099e787e7c66.png)
![Screenshot from 2022-12-02 17-27-07](https://user-images.githubusercontent.com/89972115/205351434-5ea0fdf5-3b44-4827-a79a-a7e94969c1aa.png)

**Comment by sveppalicious** [comment]
Varstu búinn að tjékka á þessu [pull request](https://github.com/hgop/syllabus-2022/pull/46#issue-1471213254)?

**Comment by gislibh** [comment]
Fallið í helpernum á víst að líta svona út 

def initialize_game() -> InitializedGame:
    response = requests.post(config.API_URL + "/create_game", json={})
    assert response.status_code == 201
