### ISSUE TITLE
Client test fails after updating to week 2 base

### ISSUE THREAD

**Issue by patrekurs19** [hgop/syllabus-2022#56]
I keep getting this error: ReferenceError: cy is not defined.
I tried adding this: /// <reference types="cypress" /> at the top of the file but it didnt fix it.

![image](https://user-images.githubusercontent.com/58478764/205517221-7e1bf6b3-5e81-4091-b935-9be73fabcaa3.png)

**Comment by Fanneyyy** [comment]
The client part is used for the e2e tests part, the instructions are there, but basically you'll need to add cypress to your application 😊

**Comment by patrekurs19** [comment]
I ran this command: npm install --save-dev --save-exact cypress
But nothing changed

**Comment by Tanges** [comment]
Followed the instructions but still getting the same error as @patrekurs19. Works fine when I'm testing in browser, any tips on how to get it through the pipes?

**Comment by finnure** [comment]
If you are working on day11 you can delete the cypress folder to fix this issue, it's not needed until you start on day12.

**Comment by patrekurs19** [comment]
Okay so we figured it out! It is a problem with the image that circleci is trying to run the test on so change node-environment to:
  node-environment:
    docker:
      - image: cypress/base:16.13.0
