### ISSUE TITLE
Capacity test að fail'a með week 2 base

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#57]
Expected
--------------------
Capacity test success

Current
--------------------
![image](https://user-images.githubusercontent.com/70693651/205520989-1293cdf2-d371-40ee-ae01-4bed60171ab7.png)

Á capacity test að fail-a s.s. partur af verkefninu eða er eitthvað annað að gerast hérna? SSLError

**Comment by finnure** [comment]
Ef þú prófar að fara inná capacity slóðina beint þá sérðu að skilríkið er vitlaust. Getur verið að þú hafir verið að breyta circleci config og breytt einhverju í create-capacity-environment job? Skoðaðu CONNECT4_SERVER_HOST environment breytuna vel. Ef hún er í lagi þá gæti þetta verið í ingress.template.yaml í k8s möppunni undir connect4-server

**Comment by KypsLloyd** [comment]
Eina sem ég bæti í create-capacity eftir week 2 baseinu voru bara chmod skipanir
![image](https://user-images.githubusercontent.com/70693651/205649468-311ccf94-3d29-40d2-8ae3-e3ec39473974.png)

server ingress:
![image](https://user-images.githubusercontent.com/70693651/205649622-c24285eb-59a7-49f3-8982-4606e1935080.png)

**Comment by KypsLloyd** [comment]
Ég fæ hins vegar no resources þegar ég keyri `kubectl get ingress -n capacity` ef það hjálpar eitthvað
![image](https://user-images.githubusercontent.com/70693651/205650545-4c881a7c-7aee-4d93-8c8b-f1ef9c37951c.png)

**Comment by KypsLloyd** [comment]
Capacity ekki priority fyrir week 3, getum commentað það út.

**Comment by siggibjarna** [comment]
þetta er það sama og ég lenti í á laugardaginn í #55 og við getum lítið gert í þessu án þess að fækka hostnames sem við notum í áfanganum - eða splitta á 2 domain
