### ISSUE TITLE
Conflicted on whether to use our code or the week 2 base

### ISSUE THREAD

**Issue by Isardadi00** [hgop/syllabus-2022#58]
I´m conflicted on whether we should continue using our code or the week 2 base.
Last I saw, the week 2 base wasn´t working properly (please correct me if I´m wrong) 
and I wanted to get started on day 11 right away.

Our code had very minor issues according to grading: 

Server failing tests on horizontal win and diagonal win. Docker compose does not connect the client to the server.

I´m wondering if we should spend the time fixing this in our code or just overwrite our entire code base with the week 2 base and continue.
I´d much rather fix our own code and see what we did wrong instead of just ignoring the mistakes
but I also don´t want to if it´s too time consuming.

What is your opinion on what we should do?

**Comment by finnure** [comment]
Sounds like the only thing you're missing is the bottom part of game_logic.py. I would check the difference with your file and the week2 base file and fix what is missing in yours. Docker compose doesn't matter for week3, but you can copy the one from week2 base and use it if you want.

**Comment by Isardadi00** [comment]
I´m currently in the midst of overwriting my server game logic.
I just got stuck in my head for a little bit, thanks for the help :)
