### ISSUE TITLE
Exam should be on Friday in the schedule

### ISSUE THREAD

**Issue by sveppalicious** [hgop/syllabus-2022#59]
In the schedule for [week 3](https://github.com/hgop/syllabus-2022/blob/main/README.md#week-3), it says the exam is on Thursday. 

> ## Week 3
> ### Starts Monday - 5. December
>  
> |                                                                      | mon                                                                     | tue                                                                                        | wed                                                                                                                                                                             | thu           | fri                              |
> | -------------------------------------------------------------------- | ----------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------- | -------------------------------- |
> | **Project**                                                    | [Database Migration & Security](/assignments/week-03/day-11/README.md) | [E2E testing](/assignments/week-03/day-12/README.md)                                                                                          |  [Monitoring and Bug reporting](/assignments/week-03/day-13/README.md)                                                                                                                                                                            |               |        [Turn in Project for week 3](/assignments/week-03/day-14/README.md)       |
> | **Schedule**                                                          | 13:30-15:30 In a classroom and via Zoom | 13:30-15:30 In a classroom and via Zoom | 13:30-15:30 In a classroom and via Zoom | Exam  |     13:30-15:00 In a classroom and via Zoom  

   
The exam is on Friday at 09:00-10:30, right?

**Comment by Fanneyyy** [comment]
Yes, def, I'll remove this, trust Canvas for all non project related things 😊
