### ISSUE TITLE
kubectl version number check in verification script

### ISSUE THREAD

**Issue by sveppalicious** [hgop/syllabus-2022#6]
In [week-01/day-03/README.md](https://github.com/hgop/syllabus-2022/tree/main/assignments/week-01/day-03#secret-and-configuration-management):

> To manage Kubernetes we can use kubectl.
> Kubectl is a command line tool to run commands agains a kubernets cluster.
>
> [Install Kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/), once you are
done verify using:
>
> ```bash
> kubectl version --client
> ```
>
> **Also remember to add `kubectl` to the setup script you created in day 1.**

Is there a specific `kubectl` version number that we should check for in the verification script?

**Comment by kthorri** [comment]
You should only check for the version that is installed when you install the cli.
