### ISSUE TITLE
just add_migration "add created field"  ekki að virka

### ISSUE THREAD

**Issue by Sigurgeirstephensen** [hgop/syllabus-2022#60]
við erum að reyna að runna just add_migration "add created field" en þegar við reyna að gera það þá kemur þetta error up 
```
just add_migration "add created field"
docker kill "${DATABASE_CONTAINER}" || true
Error response from daemon: Cannot kill container: migration_db: Container 60c098c6dc649f426287f0c27824527ec42f840ef76dfbc2c677c3e0f6698b45 is not running
docker rm "${DATABASE_CONTAINER}" || true
migration_db
docker run -d --name="${DATABASE_CONTAINER}" -e POSTGRES_USERNAME="${DATABASE_USERNAME}" -e POSTGRES_PASSWORD="${DATABASE_PASSWORD}" -e POSTGRES_DB="${DATABASE_NAME}" -p "${DATABASE_PORT}:5432" postgres:13-alpine
5c51239e79f806cf74e1e61a7c8582e8dd9f6aa6dcc7e2e8b0a29713ae9d24f7
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5432 -> 0.0.0.0:0: listen tcp 0.0.0.0:5432: bind: address already in use.
```
og við erum ekki alveg að skilja afhverju hann er að segja þetta því við erum bara að byrja á dagi 11 og við erum ekki búinir að breyta neinu nema hlutum sem við áttum að breyta fyrir þennan dag

**Comment by finnure** [comment]
Getur verið að þú sért með postgres uppsett á tölvunni þinni? Ef svo er þá er port 5432 upptekið á tölvunni og þú þarft að nota annað port. Efst í justfile er database port skilgreint sem 5432, prófaðu að breyta því í t.d. 5433. Ekki breyta því í línu 31 í justfile, það verður að vera 5432 þar. Sá partur er að vísa í portið sem postgres er að hlusta á í containernum.

**Comment by Fanneyyy** [comment]
Fixed?
