### ISSUE TITLE
Næ ekki að keyra upp clientinn minn

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#62]
Ég er að reyna að fá clientinn minn til að virka en ég er að fá 503 villu. 

Ef ég skoða Docker þá sé ekki ekkert container og ekkert images (fyrir utan postgres). Og ef ég reyni að keyra <code>just start</code> kemur eins og það sé að reyna að tala við hr_hgop-x en ég myndi vilja að það væri að tala við connect4-x.

Ég er búinn að uppfæra env variable í Cirlce Ci og keyra pipelineið aftur og síðan <code>just start</code> en sama gerist. Einhverjar hugmyndir hvað getur verið að valda því?

![Screenshot 2022-12-05 at 15 30 16](https://user-images.githubusercontent.com/19752446/205676433-1e8bc92c-73fb-4f06-af50-6af370ec36d6.png)

**Comment by Fanneyyy** [comment]
Hæhæ, ég er ekki alveg viss hvað þú ert að reyna að keyra.
ef þú ert í src/connect4-server folder og keyrir "just start", þá fæ ég engan error og allt virkar locally. Btw "just start" er bara notað fyrir local development.
Varðandi CI þá er það annað vandamál, þar ertu að deploya á k8s clusterinn þinn live, ef serverinn er ekki að virka geturu tjékkað á því hvað er í gangi með að gera "kubectl get pods". Ef einhver pod er með error þá þarf að gera "kubectl logs MY_POD_WITH_ERROR" og þá ættiru að geta séð hver errorinn er.

**Comment by finnure** [comment]
just start keyrir docker-compose.yaml. Ef þú skoðar þá skrá, er ekki einhversstaðar vísað í hr_hgop-server og client þar?
Þú ert ekki að sækja nein image fyrir server og client þegar þú keyrir docker compose, docker compose býr til sín image og keyrir þau svo upp.
[Hér](https://github.com/docker/buildx/issues/415) fékk einhver svipaða villu, lagaðist hjá einhverjum með því að nota rétt nafn á dockerfile. Getur verið að dockerfile heiti ekki Dockerfile hjá þér? Stórt D fremst og restin af stöfunum lágstafir?

**Comment by Hjortur17** [comment]
Uppraunulega þegar ég póstaði þessu þá var ég að reyna að keyra <code>just start</code> í root á verkefninu. En það sama kemur ef ég keyri þetta í <code>/connect4-client</code>. En það sem ég fæ úr server er 

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "connect4-database" (10.152.183.2), port 5432 failed: FATAL:  password authentication failed for user "hjortur17"
```

Var ekki einhvað verið að tala um þetta áðan í einhverjum þræði hér eða á Discord?

@finnure - Allir heita þeira Dockerfile (með stóru D)

**Comment by Hjortur17** [comment]
Ég er að fá <code>503 Service Temporarily Unavailable</code> þegar ég reyni að tengjast clientnum, er það ekki tengt þessu vandamáli? Búið að vera þannig síðan í gær...

**Comment by Hjortur17** [comment]
@kthorri lagaði þetta fyrir mig
