### ISSUE TITLE
Fyrirlesturinn í dag

### ISSUE THREAD

**Issue by gislig** [hgop/syllabus-2022#63]
Er nokkuð hægt að opna fyrir fyrirlesturinn í dag, þ.e. ef hann hafi verið tekinn upp?

**Comment by Fanneyyy** [comment]
@hap2000

**Comment by hap2000** [comment]
Hjartað stoppaði en hann er inn á Canvas:
https://reykjavik.instructure.com/courses/6252/external_tools/670

Getur stundum tekið einhvern tíma áður en þetta verður aðgengilegt. Alla vega kominn núna.
