### ISSUE TITLE
Nota lockfile þegar serverinn verður buildaður

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#64]
> Make sure you start using the lockfile when building the server.

Hvað þýðir þetta? 
Ég er kominn með requirements_lock.txt og recipe í Justfile, á ég að call-a það recipe í hvert skipti í þegar CI fer í gegnum server build step?

**Comment by finnure** [comment]
Við erum ekki með just installað í circleci þannig að þú getur ekki kallað í það þar. Just er bara fyrir local fikt.
requirements.txt er notað til að installa python requirements í docker file. Þú þarft að uppfæra skipunina sem installar þessum dependencies að nota lock file í staðinn fyrir requirements.txt

**Comment by KypsLloyd** [comment]
Eini staðurinn sem ég call'a á `- run: pip install -r $PROJECT_DIRECTORY/requirements.txt` er í server-lint-test job-inu... 
Á ég að installa þessum dependencies í server build jobinu í staðinn? þar sem lint-test er ekki priority í þessari viku, þaes að ég er búinn að commenta það job út

**Comment by finnure** [comment]
Þú átt ekki að breyta þessu í circleci heldur í dockerfile. ./src/connect4-server/Dockerfile

**Comment by KypsLloyd** [comment]
Roger

**Comment by finnure** [comment]
Ég fékk villu hjá mér þegar ég reyndi að keyra þetta í fyrsta skiptið. Lagaði það með því að nota python 3.11 í dockerfile í staðinn fyrir 3.9

**Comment by KypsLloyd** [comment]
Hef það í huga, takk takk!
