### ISSUE TITLE
add_migration - Næ ekki að notast við neitt úr python

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#65]
Ég er að reyna að breyta <code>add_migration</code> í Justfile-num en það er eins það finnur ekki neitt sem ég er búinn að sækja með python. Eins og til dæmis Flask eða Alembic

Hef reynt að fara í venv það breytir engu. Einhverjar hugmyndir? 

![Screenshot 2022-12-05 at 20 08 59](https://user-images.githubusercontent.com/19752446/205733199-5d26492a-eaa7-4511-b8d6-836a949ecaa3.png)

![Screenshot 2022-12-05 at 20 09 30](https://user-images.githubusercontent.com/19752446/205733267-cab9fadc-101c-4a9d-8b88-01890bca47f5.png)

**Comment by KypsLloyd** [comment]
Lenti líka í þessu, ég bætti við `python3 -m` fyrir framan flask í Justfile-num og náði að keyra. Svona:
![image](https://user-images.githubusercontent.com/70693651/205735313-b338d6f6-9095-487c-8b95-37e87d380da6.png)

**Comment by Hjortur17** [comment]
Takk fyrir!
