### ISSUE TITLE
Sentry CLI Plugin: Command failed

### ISSUE THREAD

**Issue by patrekurs19** [hgop/syllabus-2022#67]
I am not sure why this is failing, i went to the last working commit and only changed the next.config.js like @kthorri told me to do but now it wont build the client.

![image](https://user-images.githubusercontent.com/58478764/205959043-33a74d5f-c552-471b-9f37-306dfb6ce447.png)

**Comment by Hjortur17** [comment]
Er að lenda í sömu villu, var búinn að prufa að setja inn **SENTRY_AUTH_TOKEN**, **SENTRY_ORG** & **SENTRY_PROJECT** í CircleCI en virkaði ekki

**Comment by Hjortur17** [comment]
Try this solution from Finnur:

![Screenshot 2022-12-06 at 13 58 40](https://user-images.githubusercontent.com/19752446/206032109-420038fb-f683-4792-86b6-b9a163a67b00.png)

**Comment by kthorri** [comment]
Hopefully [this](https://docs.sentry.io/product/releases/setup/release-automation/circleci/) has some information

**Comment by finnure** [comment]
> Hopefully [this](https://docs.sentry.io/product/releases/setup/release-automation/circleci/) has some information

Doesn't this only apply to the python part? The next.js build contacts Sentry to create a new release, and since the build is performed inside a docker build step, the sentry auth token needs to be injected into the container for next.js build to be able to authenticate correctly with sentry.
Should we maybe unplug this feature in the next.js build and create both client and server release using sentry-cli?

**Comment by kthorri** [comment]
I see, I think either way would work.

If you were to use the sentry cli to create a "release" You would probably need to remove the "withSentry" section from next config.

If the webpack plugin is creating it automatically, injecting this into the docker container would probably be easiest

**Comment by arnarthor** [comment]
Another way (and the way I created release tracking) is to use the sentry webhook. That is just a 1 line cURL command that you can find from "Settings -> <Project> -> Release Tracking" inside the sentry console.

All you need is to set the sentry release API url in an environment variable (one URL for the client and one for the server) and then use the CIRCLE_SHA1 as your release version. That way you can also really easily tie each release to a specific github commit.

Just make sure to only run this command in the deploy step of your CI.

This way requires fewer env variables, no additional installed packages and is the same for all projects (only difference being the URL)

**Comment by arnarthor** [comment]
`https://sentry.io/settings/<your_team_name>/projects/<your_project_name>/release-tracking/` URL to documentation for this method
