### ISSUE TITLE
Næ ekki að nota cypress í CircleCi config

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#68]
Hef reynt bæði að keyra <code>npm run cypress:headless</code> en þá fæ ég villuna 

```
It looks like this is your first time using Cypress: 9.1.1

Your system is missing the dependency: Xvfb
```

Þannig ég reyndi að notast við cypress <code>orb</code> (<code>cypress: cypress-io/cypress@2.2.0</code>) en þá fæ ég 

```
Orb cypress-io/cypress@2.2.0 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.
```

Hver er lausnin við þessu? Er fólk að nota npm pakkann eða orb?

**Comment by sveppalicious** [comment]
Ég lenti í sömu villu. Til að nota þetta orb þarftu að leyfa third party orbs í Organization Security settings á CircleCi. Ég endaði samt með að nota bara docker image af Cypress, svipað og í hinum jobsunum í config.yml

```yaml
e2e-test:
    docker:
      - image: xxxxxx
```

Þessi [docs](https://docs.cypress.io/guides/continuous-integration/circleci#Additional-Examples) hjálpuðu helling. Ég er samt að sleppa öllu restore/save cache stöffinu.

**Comment by Hjortur17** [comment]
Þetta leysti vandamálið! En ertu þú með harð kóðað baseUrl inn í cypress.json? 

```
"baseUrl": "{{API_URL}}",
```

Ég reyndi að notast við env variable en þá fæ ég villu: 

```
Expected `baseUrl` to be a fully qualified URL (starting with `http://` or `https://`). Instead the value was: `"{{API_URL}}"`
```

Samt er ég með <code>API_URL</code> set í environment:

```
environment:
      PROJECT_DIRECTORY: ./src/connect4-client
      API_URL: "http://connect4.acceptance.b3g.hgopteam.com"
```

**Comment by sveppalicious** [comment]
Ég er með það harðkóðað í `cypress.json` eins og er. Það hljómar eins og að það sé í lagi samkvæmt [leiðbeiningunum](https://github.com/hgop/syllabus-2022/tree/main/assignments/week-03/day-12#what-is-cypress) en ég er ekki 100% viss.

**Comment by Hjortur17** [comment]
Fann út úr því hvernig þú getur bætt við env. Þú settur bara það sem url sem þú vilt hafa sem default í cypress.json en síðan setturu í envoiroment í config.yaml:

```
cypress_baseUrl: "http://connect4.acceptance.b3g.hgopteam.com"
```

Er reyndar að fá 404 villu þegar það reynir að kalla á þetta url. Ertu að keyra test eftir deploy? (Ég er að keyra það á milli build-publish og deploy)

**Comment by sveppalicious** [comment]
Ég er að keyra `e2e-test` á eftir `create-acceptance-environment`. Þú villt bæta við skrefi í `create-acceptance-environment` þar sem að þú deployar clientinn, ásamt servernum.
