### ISSUE TITLE
Could not connect to server..... Port 5432

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#72]
![image](https://user-images.githubusercontent.com/70693651/206255285-4d3a7f12-5c77-4884-bc27-5b87903fd271.png)
Veit einhver hvað er að?

Er búinn að prófa delete-a databaseinn og apply-a svo aftur
Termnialið vinstri er eftir skipuninni `kubectl logs connect4-migrations-6pxrq -n acceptance`

**Comment by Fanneyyy** [comment]
Það lítur út eins og databaseinn hafi ekki verið ready þegar migrations reyndu að keyra, en það var retried, tveimur línum neðar og þar er það Completed. Voru testin ekki success? Annars má alveg sleppa að keyra acceptance tests á server í þessari viku, einungis required að deploya client á acceptance og keyra e2e testin 😊

**Comment by KypsLloyd** [comment]
Takk takk, þetta er komið!
