### ISSUE TITLE
CORS villa eftir að hafa bætt við Sentry

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#73]
Eftir að hafa bætt við Sentry í forritið þá er ég byrjaður að fá CORS villu, einhver hugmynd hvernig er hægt að leysa það?

![Screenshot 2022-12-08 at 14 49 35](https://user-images.githubusercontent.com/19752446/206477544-80f1c725-5dfe-476b-b683-8ca1fdf98057.png)

**Comment by arnarthor** [comment]
Tékkaðu á `kubectl logs <pod-nafn>`. Líklegast ertu að fá 500 villu útaf einhverju, en það kemur fram sem CORS villa.

**Comment by Hjortur17** [comment]
Fæ þetta við að kalla á serverinn

<img width="875" alt="Screenshot 2022-12-09 at 15 02 36" src="https://user-images.githubusercontent.com/19752446/206731255-5e73b6b1-1ee2-4d95-a102-2a641c41d4a2.png">

**Comment by Hjortur17** [comment]
Fékk þetta til að virka með því að taka acceptance test út og setja það aftur inn
