### ISSUE TITLE
Must provide --username with --password-stdin

### ISSUE THREAD

**Issue by ElinVilbergs** [hgop/syllabus-2022#74]
Gafst upp á kóðanum mínum þar sem eitthvað var brotið og sótti viku 2 base á þriðjudaginn.

Ég er búin að fara yfir öll skjöl og breyta team name og docker repo fields en er samt alltaf að fá þessa villu, bæði í build-publish-server og build-publish-client:

![Screenshot 2022-12-08 at 16 06 51](https://user-images.githubusercontent.com/34030656/206498562-f88577b2-6a4c-4ce5-aaa1-6dedcad7f04a.png)

Spá hvort ég hafi gleymt einhverju skrefi en ég er búin að fara yfir viku 1 og viku 2 til að athuga það og finn ekki neitt.
Pældi í því hvort það sé eitthvað vitlaust skrifað hjá mér í config.yml en það virðist vera allt rétt þegar ég ber saman við hjá öðrum. Kannski eitthvað vitlaust í Docker hjá mér?

**Comment by Fanneyyy** [comment]
ertu búin að setja ENV variable-ið í project settings inní Circle CI?

**Comment by ElinVilbergs** [comment]
Heyrðu jú, sé að það var ritvilla í nafninu hjá mér inni í Circle CI 😅  Búin að laga það og fæ núna success :D
![Screenshot 2022-12-08 at 17 14 58](https://user-images.githubusercontent.com/34030656/206519287-bdc1b3f7-ee98-4acd-9853-784aeff2f4cd.png)

Týpískt að það var ekkert flóknara en það haha
