### ISSUE TITLE
Bara til að vera viss varðandi skil

### ISSUE THREAD

**Issue by KypsLloyd** [hgop/syllabus-2022#75]
megum við sleppa testin sem er merkt í gulu? Þ.a.e.s  mega þær faila í circle ci pipline-inu (við kommentum það bara út).
![image](https://user-images.githubusercontent.com/70693651/206726010-441a2afa-6232-4b89-80b8-09abd3a60ed9.png)

En við þurfum að láta e2e, client acceptance environment og sentry dæmið virka.

**Comment by KypsLloyd** [comment]
Unit testið þarf nátturlega að virka fyrir nýja ''created'' parameter, en er í lagi að sleppa hinn 3?

**Comment by kthorri** [comment]
Virka hin testin ekki?

Það væri ideal ef þið værum með pipelineið keyrandi eins og það ætti að vera.

Við tókum vissulega fram að það mætti taka einhverja hluta af þessu út á meðan þið væruð að vinna í vikunni. 

Það sem verður til námsmat fyrir þessa viku eru 

* Migration (þá þarf að sjálfsögðu að uppfæra testin sem þarf að uppfæra í unit / acceptance sem part af þeirri breytingu)
* E2E
* Dependabot
* Sentry

Það er samt klárlega hægt að fá einhverja plúsa fyrir að vera með mjög gott pipeline :)
